Update 11.5.2.14 Programmatisch steuerbare Texteinfügemarke und Selek…
BIK-BITV/BIK-App-Test pull request #41
Opened 2021-07-04 16:12 UTC by johannesFischer84

Ergänzt bzw. etwas deutlicher gemacht, dass der Fokus zwischen Bedienelementen versetzt werden können muss, nicht nur innerhalb eines Eingabefelds

2021-07-06 11:32 UTC, detlevhfischer commented on Prüfschritte/de/11.5.2.13 Fokusverfolgung Texteinfügemarke und Textauswahl.adoc
> +* Wird die Position der Texteinfügemarke vom Screenreader ausgegeben?
Ich denke, die Beschreibung ist etwas missverständlich. So wird bei incrementeller Auswahl in OS z.B. nicht immer der ganze zuvor ausgewählte Text ausgegeben, sondern der zusätzlich ausgewählte. Bei verringerung der Answahl wird der nun nicht mehr ausgewählte Bestandteil mit Zusatz "nicht ausgewählt" ausgegeben, als gerade nicht der ausgewählte Text. Da sich die Mechanismen der Auswahl und der Vermittlung von ausgewäghlten und nicht ausgewähltem Text je nach Screenreader und OS und auch zukünftig unterscheiden können, finde ich eine generellere Prüfung im Sinne von "Unterstützt der Inlat, soweit verfügbar, die vom System und Screenreader vorgesehenen mechanismen der Textauswahl?" Das scheint mir in der bestehenden Prüfanleitung besser umgesätzt als in dieser Umformulierung.

2021-07-06 11:34 UTC, detlevhfischer requested changes
Siehe Kommentar zur Prüfanleitung, die hier denke ich etwas zu spezifisch ist und deshalb möglicherweise zu Fehlbewertungen führt.

2021-07-06 13:42 UTC, johannesFischer84 commented
@detlevhfischer Detlev, danke für den Hinweis zu den Unterschieden. Ich habe deinen Vorschlag für Position der Texteinfügemarke und den markierten Text übernommen, wobei ich die beiden Punkte in Klammern nochmal benannt habe. Falls es noch nicht passt, kommentiere gern nochmal.

Die Änderung müsste innerhalb des Pull Requests jetzt sichtbar sein. Falls nicht, gerne Bescheid sagen (ich habe zum ersten Mal einen Pull Request angepasst).

2021-07-07 13:47 UTC, detlevhfischer reviewed
Fokusversetzung zu anderen Elementen scheint mir hier nicht reinzugehören.

2021-07-07 13:47 UTC, detlevhfischer commented on Prüfschritte/de/11.5.2.14 Programmatisch steuerbare Texteinfügemarke und Selektion.adoc
> +* Fokus zwischen Bedienelementen lässt sich mit aktiviertem Screenreader versetzen
Ist das nicht ein Punkt, der schon unter X.2.4.3 unf ggf. X.3.2.1 abgedeckt ist? Mir scheint es, hier geht es um die Bearbeitung z.B. zum Zwecke von Copy und Paste oder für Textkorrekturen (Fokussierung, Auswahl von Text).

2021-07-07 15:49 UTC, johannesFischer84 commented
Du hast Recht. Ich hatte die Fokusversetzung zwischen Bedienelementen drin, weil ich den Unterschied der Begriffe "focus" und "text insertion point" nicht verstanden habe. Letzteres ist wohl die Texteinfügemarke und der Fokus ist wohl entweder allgemein gemeint oder bezieht sich auf irgendwelche Unterelemente.

Die Idee zu den Anleitungen spezifisch zu Screenreader/Betriebssystem zur Textauswahl finde ich gut. Ich habe deinen Link zu iOS eingetragen. Außerdem habe ich zu Android etwas gesucht und auch ausprobiert. Da habe ich gleich ein paar Punkte zu Android eingetragen sowie Quellen dazu verlinkt. Ein iOS-Gerät habe ich gerade nicht greifbar, daher habe ich da noch keine Einzelpunkte notiert.

2021-07-07 15:50 UTC, johannesFischer84 commented on Prüfschritte/de/11.5.2.14 Programmatisch steuerbare Texteinfügemarke und Selektion.adoc
> +* Fokus zwischen Bedienelementen lässt sich mit aktiviertem Screenreader versetzen
Eine Abgrenzung der beiden Schritte habe ich unter Hinweisen ergänzt.

2021-07-16 09:42 UTC, merged