Update 11.1.1.1c Leere alt-Attribute für Layout-Grafiken.adoc
BIK-BITV/BIK-App-Test pull request #55
Opened 2021-09-09 13:00 UTC by sweckenmann

Vollständige Überarbeitung (auch Änderung des Prüfschritt-Namens)

2021-09-09 13:03 UTC, sweckenmann commented
Bitte prüfen: 
- neuer Prüfschritt-Name okay?
- Formulierung: "Grafiken, die nicht informationstragend sind sollen nicht fokussierbar sein, es sollte keine Ausgabe durch den Screenreader erfolgen." --> Ist die Formulierung "sollen nicht fokussierbar sein" korrekt? Nach meinem Verständnis bewirkt die entsprechende Technik für die Auszeichnung dekorativer Grafiken, dass keine Screenreader-Ausgabe erfolgt UND dass die Grafik nicht fokussiert wird. Daher habe ich beide Aspekte in der Formulierung.

2021-11-16 07:38 UTC, detlevhfischer commented
Ich würde diesen Prüfschritt lieber streichen und bei 9.1.1.1a und b unterbringen, je nach dem ob Deko mit verlinkt oder unverlinkt...
siehe #49

2021-11-16 07:39 UTC, detlevhfischer requested changes
Wie gesagt ich bin eher für Verteilen auf 11.1.1.1a unf 11.1.1.1b

2022-01-21 09:39 UTC, detlevhfischer requested changes
Ich denke, wir könnten den Prüfschritt einsparen und dekorative Grafiken bei 11.1.1.1b mittesten. 
Was wir dringend brauchen. ist der Prüfschritt, dass informationstragende Inhalte überhaupt ausgegeben / fokussiert werden.

2022-01-21 11:25 UTC, sweckenmann commented
Ok, versuche mich in einem PR für 11.1.1.1a und 11.1.1.1b, wo ich das mit unterbringe.

Wenn wir für dekorative Grafiken die Anforderung definieren:  "Dekorative Grafiken sollen nicht fokussiert werden, es soll keine SR-Ausgabe erfolgen" wäre das Gegenstück "Informationstragende Grafiken sollen mit Wichgesten-Navigation fokussiert werden und eine Textalternative wird vom SR ausgegeben. Einen extra Prüfschritt bräuchten wir nicht?

Denn: Wenn ich es richtig verstehe, dann kann man auch bei Apps Grafiken "als dekorativ" auszeichnen und das hat zur Folge, dass sie bei Wischgesten-Navigation nicht erreicht werden. Für informationstragende Grafiken könnte diese Auszeichnung missbräuchlich geschehen, das wäre dann das Problem?

Ein abweichendes Verhalten Tastatur / Wischgesten bei interaktiven Elementen ist ja nochmal ne andere Baustelle.

2024-09-30 16:58 UTC, closed without merging