11.1.4.4 zoom auf 200%
BIK-BITV/BIK-App-Test pull request #84
Opened 2022-02-08 16:36 UTC by sweckenmann

- Hinweise überarbeitet
- Artikel als Quelle hinzugefügt

2022-02-09 09:55 UTC, detlevhfischer requested changes
Siehe Kommentare unten.

2022-02-09 09:55 UTC, detlevhfischer commented on Prüfschritte/de/11.1.4.4 Text auf 200% vergrößerbar.adoc
> +* Die Zoomfunktion (Vergrößerung des gesamten Bildausschnitts) des Betriebssystems wird in der Regel eine 200%ige Vergrößerung ermöglichen. Funktioniert die Zoomfunktion mit der zu testenden Software
Typos: Textvergrößerung unterstützen

(Vergrößerung des gesamten Bildausschnitts)
DF: Der Bildausschnitt *verkleinert* sich in der Vergrößerung, die Formulierung ist unglücklich.

DF: Was unterstützt werden sollte, ist ja nicht eigentlich die Textvergrößerungsfunktion, sondern der Einsatz von dynamic fonts, auf die sich die Textvergrößerungsfunktion dann tatsächlich auswirkt (da müsste man noch mal checken, wie die bei iOS und Android genau heißen).

2022-02-09 10:53 UTC, sweckenmann commented
Bitte nochmal lesen. Habe den Hinweis-Teil nochmal umgeschrieben (dynamischer Text) und als Quelle einen Artikel hinzugefügt: https://medium.com/@r.whitaker/swiftui-accessibility-dynamic-type-d9b99ae87334
Mach sonst gerne einen Vorschlag bzgl. dynamischer Schriften.

2022-02-09 14:58 UTC, detlevhfischer requested changes
siehe Kommentar unten

2022-02-09 14:58 UTC, detlevhfischer commented on Prüfschritte/de/11.1.4.4 Text auf 200% vergrößerbar.adoc
> +Native mobile Plattformen verfügen über eine Funktion "größerer dynamischer Text" das bedeutet, eine Funktion zur Textvergrößerung. Apps, die diese Funktion unterstützen, passen sich an die festgeleg
Komma nach "größerer dynamischer Text"
Apps, die dynamische Fonts verwenden, passen diese an die eingestellte Schriftgröße an.

Bei dem Rest bin ich mit noch unsicher, ob wir das so wirklich drinlassen sollten. Warumgerade hier dringende Empfehlung an App-Entwickler, in einem Prüfschritt? Sollen wir dann auch schreiben: Wir empfehlen dringend, Überschriften einzusetzen, die Tastaturreihenfolge richtig umzusetzen usw. usf.? 

Und was genau kann man sich unter "Probleme, die bei der Nutzung der dynamischen Textfunktion entstehen" vorstellen? Dynamische Fonts in Toolbars, so dass Texte abgeschnitten werden oder Dinge komisch umbrechen? Oder umgekehrt, manche Inhalte vergößern dynamisch, andere nicht?

Wenn's dinbleibt: Probleme (Komma) die...

2022-02-09 15:17 UTC, sweckenmann commented
@detlevhfischer Du kennst dich technisch besser aus, formuliere gerne um oder schmeiß den Absatz unter Hinweise raus. Du kannst ja in den PR auch reinarbeiten.

2024-11-20 09:57 UTC, detlevhfischer commented
Hinfällig.

2024-11-20 09:57 UTC, closed without merging